language: python
python:
    - "3.4"
    - "3.5"
# command to install dependencies
install: "pip install '.[test]' -r requirements.txt"
# command to run tests
script: py.test --cov-report= --cov=src/meteoservice test/
