language: python
python:
    - "3.4"
    - "3.5"

# dependencies
cache:
    directories:
        - $PWD/wheelhouse
install:
    - pip wheel --find-links=wheelhouse -r requirements-dev.txt
    - pip install --use-wheel --no-index --find-links=wheelhouse -r requirements-dev.txt
    - pip install -e .

# tests
script: py.test --cov-report= --cov=src/meteoservice test/

# send coverage to scrutinizer
after_script:
    - pip install scrutinizer-ocular
    - ocular
