language: python
python:
    - "3.4"
    - "3.5"

# dependencies
install:
    - pip install -U pip # with older pip extras_require doesn't work
    - "pip install '.[test]' -r requirements.txt"

# tests
script: py.test --cov-report= --cov=meteoservice test/
